forms/baseform.py
from wtforms import Form


class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors)
        return message_list

    # 这段代码定义了一个表单基类BaseForm，
    # 它添加了一个messages属性，该属性收集表单中所有字段的错误消息，并以列表的形式返回它们。这可以用于在用户界面上显示错误消息。

blueprints/front.py
from flask import Blueprint, request, render_template, jsonify, current_app, url_for, send_from_directory, g, abort, \
    redirect, flash
from werkzeug.utils import secure_filename
import os
from models.post import PostModel, BoardModel, CommentModel
from exts import csrf, db
from decorators import login_required
from forms.post import PublicPostForm, PublicCommentForm
from utils import restful
from flask_paginate import Pagination
from sqlalchemy import text

bp = Blueprint("front", __name__, url_prefix="")


@bp.route("/")
def index():
    boards = BoardModel.query.filter_by(is_active=True).all()

    # 获取页码参数
    page = request.args.get("page", type=int, default=1)
    # 获取板块参数
    board_id = request.args.get("board_id", type=int, default=0)

    # 当前page下的起始位置
    start = (page - 1) * current_app.config.get("PER_PAGE_COUNT")
    # 当前page下的结束位置
    end = start + current_app.config.get("PER_PAGE_COUNT")

    # 查询对象
    query_obj = PostModel.query.filter_by(is_active=True).order_by(PostModel.create_time.desc())
    # 过滤帖子
    if board_id:
        query_obj = query_obj.filter_by(board_id=board_id)
    # 总共有多少帖子
    total = query_obj.count()

    # 当前page下的帖子列表
    posts = query_obj.slice(start, end)

    # 分页对象
    pagination = Pagination(bs_version=4, page=page, total=total, outer_window=0, inner_window=2, alignment="center")

    context = {
        "posts": posts,
        "boards": boards,
        "pagination": pagination,
        "current_board": board_id
    }
    current_app.logger.info("index页面被请求了")
    return render_template("front/index.html", **context)


@bp.route("/post/public", methods=['GET', 'POST'])
@login_required
def public_post():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template("front/public_post.html", boards=boards)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            # author_id = form.author_id.data
            post = PostModel(title=title, content=content, board_id=board_id, author=g.user, author_id=g.user.id)
            db.session.add(post)
            db.session.commit()
            return restful.ok()
        else:
            message = form.messages[0]
            return restful.params_error(message=message)


@bp.route('/image/<path:filename>')
def uploaded_image(filename):
    path = current_app.config.get("UPLOAD_IMAGE_PATH")
    return send_from_directory(path, filename)


@bp.post("/upload/image")
@csrf.exempt
@login_required
def upload_image():
    f = request.files.get('image')
    extension = f.filename.split('.')[-1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:
        return jsonify({
            "errno": 400,
            "data": []
        })
    filename = secure_filename(f.filename)
    f.save(os.path.join(current_app.config.get("UPLOAD_IMAGE_PATH"), filename))
    url = url_for('front.uploaded_image', filename=filename)
    return jsonify({
        "errno": 0,
        "data": [{
            "url": url,
            "alt": "",
            "href": ""
        }]
    })


@bp.get("/post/detail/<int:post_id>")
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post.is_active:
        return abort(404)
    post.read_count += 1
    db.session.commit()
    return render_template("front/post_detail.html", post=post)


# @bp.post("/post/<int:post_id>/comment")
# @login_required
# def public_comment(post_id):
#     form = PublicCommentForm(request.form)
#     if form.validate():
#         content = form.content.data
#         comment = CommentModel(content=content, post_id=post_id, author=g.user, author_id=g.user.id)
#         db.session.add(comment)
#         db.session.commit()
#     else:
#         for message in form.messages:
#             flash(message)
#
#     return redirect(url_for("front.post_detail", post_id=post_id))


def check_comment_length(func):
    def wrapper(comment):
        if len(comment) < 2 or len(comment) > 200:
            raise ValueError("评论长度必须在2到200个字符之间")
        return func(comment)

    return wrapper



def create_trigger():
    # 检查触发器是否已经存在
    trigger_query = "SHOW TRIGGERS LIKE 'before_insert_comment'"
    # with db.engine.connect() as connection:
    result = db.session.execute(text(trigger_query))
    result = db.session.execute("SHOW TRIGGERS LIKE 'before_insert_comment'")
    existing_trigger = result.fetchone()

    # 如果触发器不存在，则创建触发器
    if not existing_trigger:
        # 创建触发器的 SQL 语句
        create_trigger_query = '''
            CREATE TRIGGER before_insert_comment
            BEFORE INSERT ON comment
            FOR EACH ROW
            BEGIN
                DECLARE comment_length INT;
                SET comment_length = CHAR_LENGTH(NEW.content);

                IF comment_length < 2 OR comment_length > 200 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = '评论长度必须在2到200个字符之间';
                END IF;
            END;
        '''

        # 执行创建触发器的 SQL 语句
        # with db.engine.connect() as connection:
        db.session.execute(text(create_trigger_query))

        print("触发器创建成功！")
    else:
        print("触发器已经存在，无需重复创建。")

@login_required
@bp.post("/post/<int:post_id>/comment")
def public_comment(post_id):
    try:
        form = PublicCommentForm(request.form)
        # if form.validate():
        content = form.content.data
        new_comment = CommentModel(content=content, post_id=post_id, author=g.user, author_id=g.user.id)
        db.session.add(new_comment)
        # 在评论添加到数据库之前创建触发器
        # create_trigger()
        db.session.commit()
        print("评论已添加：", post_id)
        flash("评论已添加")
        return redirect(url_for("front.post_detail", post_id=post_id))
    except Exception as e:
        print("添加评论失败：", e)
        flash("添加评论失败，请输入2-200字符")
        return redirect(url_for("front.post_detail", post_id=post_id))

# @bp.post("/post/<int:post_id>/comment")
# @login_required
# def public_comment(post_id):
#     form = PublicCommentForm(request.form)
#     if form.validate():
#         content = form.content.data
#         comment = CommentModel(content=content, post_id=post_id, author=g.user, author_id=g.user.id)
#         db.session.add(comment)
#         db.session.commit()
#     else:
#         for message in form.messages:
#             flash(message)
#
#     return redirect(url_for("front.post_detail", post_id=post_id))


@bp.route("/search")
def search():
    # /search?q=flask
    # /search/<q>
    # post，request.form
    q = request.args.get("q")
    # posts = PostModel.query.filter(PostModel.title.contains(q)).all()
    boards = BoardModel.query.filter_by(is_active=True).all()

    # 获取页码参数
    page = request.args.get("page", type=int, default=1)
    # 获取板块参数
    board_id = request.args.get("board_id", type=int, default=0)

    # 当前page下的起始位置
    start = (page - 1) * current_app.config.get("PER_PAGE_COUNT")
    # 当前page下的结束位置
    end = start + current_app.config.get("PER_PAGE_COUNT")

    # 查询对象
    # query_obj = PostModel.query.filter_by(is_active=True).order_by(PostModel.create_time.desc())
    posts = PostModel.query.filter(PostModel.title.contains(q)).order_by(PostModel.create_time.desc())
    # 过滤帖子
    if board_id:
        # posts = posts.filter_by(board_id=board_id)
        posts = posts.filter_by(board_id=board_id)
    # 总共有多少帖子
    total = posts.count()

    # 当前page下的帖子列表
    posts = posts.slice(start, end)

    # 分页对象
    pagination = Pagination(bs_version=4, page=page, total=total, outer_window=0, inner_window=2, alignment="center")

    context = {
        "posts": posts,
        "boards": boards,
        "pagination": pagination,
        "current_board": board_id
    }
    current_app.logger.info("index页面被请求了")
    return render_template("front/index.html", **context)


@bp.get("/laws")
def laws():
    return render_template("front/laws.html")

# @bp.get('/user_comments_view')
# def user_comments_view():
#     # 执行查询操作，获取view2的数据
#     query = text('SELECT * FROM user_comments_view')
#     result = db.session.execute(query)
#     view2_data = result.fetchall()
#     # 渲染admin.html视图，并将查询结果传递给模板
#     return render_template('view/user_comments_view.html', view2_data=view2_data)

blueprints/user.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for, flash, session, g, \
    render_template_string, jsonify
from exts import db, mail
from werkzeug.security import generate_password_hash, check_password_hash
import random
from utils import restful
from forms.user import RegisterForm, LoginForm, EditProfileForm
from models.user import UserModel
from models.post import *
from models.email import EmailCaptchaModel
from decorators import login_required
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
import os
import string
from flask_mail import Message

bp = Blueprint("user", __name__, url_prefix="/user") # 这个页面的URL需要使用/user索引


# @bp.route("/register", methods=['GET', 'POST'])
# def register():
#     if request.method == 'GET':
#         return render_template("front/register.html")
#     else:
#         form = RegisterForm(request.form)
#         if form.validate():
#             email = form.email.data
#             username = form.username.data
#             password = form.password.data
#             user = UserModel(email=email, username=username, password=password)
#             db.session.add(user)
#             db.session.commit()
#             return redirect(url_for("user.login"))
#         else:
#             for message in form.messages:
#                 flash(message)
#             return redirect(url_for("user.register"))


# GET:从服务器上获取数据
# POST：将客户端的数据提交给服务器
@bp.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'GET':
        # 如果是 GET 请求，返回注册页面模板
        # return render_template("register.html")
        return render_template("front/register.html", form=form)
    elif request.method == 'POST':
        # 验证用户提交的邮箱和验证码是否对应且正确
        # #表单验证:flask-wtf: wtforms
        form = RegisterForm(request.form)  # 自动验证
        if form.validate():  # 自动调用RegisterForm类中的验证器
            # 如果表单验证通过，获取表单中用户输入的邮箱、用户名和密码
            email = form.email.data
            username = form.username.data
            password = form.password.data
            # 创建一个新用户对象，并将用户输入的信息存储到数据库中
            user = UserModel(email=email, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            # 注册成功后重定向用户到登录页面
            return redirect(url_for("user.login"))
        else:
            # 如果表单验证不通过，打印表单验证错误信息到控制台，并重定向用户回到注册页面
            print(form.errors)
            # return redirect(url_for("auth.register"))
            return render_template_string('''
        <script>
            alert('请重新输入');
            window.location.href = "{{ url_for('user.register') }}";
        </script>
    ''')


@bp.route("/captcha/email")
def mail_captcha():
    try:
        # /captcha/email/<email>
        # /captcha/email?email=xxx@qq.com
        email = request.args.get("email")  # 得到目标邮件的地址
        # 4/6: 随机数组、宁母、数组和字母的组合
        source = string.digits * 6
        captcha = random.sample(source, 6)
        # print(captcha)
        captcha = "".join(captcha)
        message_body = f"【南开大学校园集市论坛】您的验证码是{captcha}，请勿告诉别人！"
        message = Message(subject="南开大学校园集市论坛验证码", recipients=[email], body=message_body)
        mail.send(message)
        # memcached/redis
        # 用数据库表的方式存储
        email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
        db.session.add(email_captcha)
        db.session.commit()
        # RESTful API->code": 200表示相应正常
        return jsonify({"code": 200, "message": "", "data": None})
    except Exception as e:
        print(e)
        return restful.server_error()


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            a = user.check_password(password)
            if user and user.check_password(password):
                if not user.is_active:
                    flash("该用户已被禁用！")
                    return redirect(url_for("user.login"))
                session['user_id'] = user.id
                if remember:
                    session.permanent = True
                return redirect("/")
            else:
                flash("邮箱或者密码错误！")
                return redirect(url_for("user.login"))
        else:
            for message in form.messages:
                flash(message)
            return render_template("front/login.html")


# # 如果没有指定methods参数，默认就是get请求
# @bp.route("/login", methods=['GET', 'POST'])
# def login():
#     if request.method == 'GET':
#         return render_template("front/login.html")
#     else:
#         form = LoginForm(request.form)
#         if form.validate():
#             email = form.email.data
#             password = form.password.data
#             user = UserModel.query.filter_by(email=email).first()
#             if not user:
#                 print("邮箱在数据库中不存在")
#                 return redirect(url_for("user.login"))
#             if check_password_hash(user.password, password):
#                 # cookie:一般用来存放登录和授权你的东西
#                 # flask中的session是通过加密以后存放在cookie中的
#                 session['user_id'] = user.id
#                 # 这行代码在登录成功之后会被放在cookie中，在以后访问其他页面的时候会被交给其他页面用来快速登录
#                 return redirect("/")
#             else:
#                 print("密码错误")
#                 return redirect(url_for("user.login"))
#         else:
#             print(form.errors)
#             return

@bp.get('/logout')
def logout():
    session.clear()
    return redirect("/")


@bp.get("/profile/<string:user_id>")
def profile(user_id):
    user = UserModel.query.get(user_id)
    is_mine = False
    if hasattr(g, "user") and g.user.id == user_id:
        is_mine = True
    context = {
        "user": user,
        "is_mine": is_mine
    }
    print(user)
    return render_template("front/profile.html", **context)


@bp.post("/profile/edit")
@login_required
def edit_profile():
    form = EditProfileForm(CombinedMultiDict([request.form, request.files]))
    if form.validate():
        username = form.username.data
        avatar = form.avatar.data
        signature = form.signature.data

        # 如果上传了头像
        if avatar.startswith("http"):
            g.user.avatar = avatar
        elif avatar.startswith("上传头像链接"):
            pass
        elif avatar:
            # 生成安全的文件名
            filename = secure_filename(avatar.filename)
            # 拼接头像存储路径
            avatar_path = os.path.join(current_app.config.get("AVATARS_SAVE_PATH"), filename)
            # 保存文件
            avatar.save(avatar_path)
            # 设置头像的url
            g.user.avatar = url_for("media.media_file", filename=os.path.join("avatars", filename))
        # g.user.avatar = avatar
        g.user.username = username
        g.user.signature = signature
        db.session.commit()
        return redirect(url_for("user.profile", user_id=g.user.id))
    else:
        for message in form.messages:
            flash(message)
        return redirect(url_for("user.profile", user_id=g.user.id))


@bp.route("/mail/test")
def mail_test():
    message = Message(subject="邮箱测试", recipients=["1504411960@qq.com"], body="这是一条测试邮件")
    mail.send(message)
    return "邮件发送成功"


@bp.post('/logoff')
def logoff():
    session_data = dict(session)
    user_id = session['user_id']
    this_user = UserModel.query.filter_by(id=user_id).first()

    try:
        # 查询帖子
        posts = PostModel.query.filter_by(author=this_user).all()  # post返回值为course_id主键查询的帖子
        # print(post.id)
        if posts is None:
            raise Exception('Course not found.')
        # # 删除关联的帖子记录
        # enrollments = PostModel.query.filter_by(board_id=this_user).all()

        for post in posts:
            db.session.delete(post)
            # 删除关联的帖子记录
            enrollments = CommentModel.query.filter_by(post_id=post.id).all()
            for enrollment in enrollments:
                db.session.delete(enrollment)
        committes = CommentModel.query.filter_by(author_id=user_id).all()
        for committe in committes:
            db.session.delete(committe)

        # 删除自己
        db.session.delete(this_user)

        # # 删除模块
        # db.session.delete(board)
        # 提交事务
        db.session.commit()
        session.clear()
        return restful.ok()
    except Exception as e:
        # 出现异常时回滚事务
        db.session.rollback()
        return 'Course withdrawal failed: ' + str(e)

templates/front/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static',filename='common/zlajax.js') }}"></script>
    <script src="{{ url_for('static',filename='front/js/base.js') }}"></script>
    {#    <script src="{{ url_for('static',filename='front/js/base.js') }}"></script>#}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/base.css') }}">
    {#    <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='front/css/custom.css') }}">#}
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/" target="_blank">南开大学校园集市论坛</a>
    <a style="color: #db4055" class="navbar-brand"
       href="https://tieba.baidu.com/f?ie=utf-8&kw=%E5%8D%97%E5%BC%80%E5%A4%A7%E5%AD%A6"
       target="_blank">南开大学贴吧入口</a>
    <a class="navbar-brand" href="{{ url_for('front.laws') }}" target="_blank">论坛使用说明</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/" target="_blank">首页 <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <form class="form-inline my-lg-0" method="GET" action="{{ url_for('front.search') }}">
            <input class="form-control mr-sm-2" type="search" placeholder="请输入关键字" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
        <ul class="navbar-nav ml-4">
            {% if g.user %}
                {% if g.user.is_staff %}
                    <li class="nav-item">
                        <a href="{{ url_for('cms.index') }}" target="_blank" class="nav-link">管理系统</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{{ url_for('user.profile',user_id=g.user.id) }}" class="nav-link">{{ g.user.username }}</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('user.profile', user_id=g.user.id) }}" class="nav-link">
                        <span style="background-image: url({{ g.user.avatar }}); display: inline-block; width: 50px; height: 50px; background-size: cover; background-repeat: no-repeat;"></span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for("user.logout") }}" class="nav-link">退出登录</a>
                </li>
                <li class="nav-item">
                    {#                    <a href="{{ url_for("user.logoff") }}" method="post" class="nav-link">注销账号</a>#}
                    <form action="{{ url_for('user.logoff') }}" method="post">
                        <button type="submit" class="nav-link" id="logoff">注销账号</button>
                        <div id="logoff_link" data-url="{{ url_for('user.register') }}"></div>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="main-container" style="color: #BC8F8F">
    <div class="mouse"></div> <!-- 使用一个 div 元素作为鼠标指针 -->
    {% block body %}{% endblock %}
</div>
{# <video src="https://c-ssl.dtstatic.com/uploads/item/201808/01/20180801054113_pfnci.thumb.1000_0.gif" class="bjimg" autoplay loop muted></video>#}
{#<div class="mybox"></div>#}
</body>
</html>

templates/front/index.html
{% extends "front/base.html" %}

{% block title %}南开大学校园集市论坛{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-group">
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="post-info-group">
                            <p class="post-title">
                                <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                            </p>
                            <p class="post-info">
                                <span>作者：{{ post.author.username }}</span>
                                <span>发表时间：{{ post.create_time }}</span>
                                <span>评论：{{ post.comments.all()|length }}</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {{ pagination.links }}
        </div>
    </div>
    <div class="sm-container">
        <div style="padding-bottom:10px;">
            <a href="{{ url_for("front.public_post") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
            {% for board in boards %}
                {% if board.id == current_board %}
                    <a href="{{ url_for('front.index',board_id=board.id) }}"
                       class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for('front.index',board_id=board.id) }}"
                       class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/front/login.html
{% extends 'front/base.html' %}

{% block title %}
    登录
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/sign.css') }}">
{% endblock %}

{% block body %}
    <h1 class="page-title">登录</h1>
    <div class="sign-box">
        <form action="{{ url_for('user.login') }}" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="邮箱">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="密码">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember" value="1">记住我
                </label>
            </div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="form-group">
                        <ul>
                            {% for message in messages %}
                                <li class="text-danger">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endwith %}
            <div class="form-group">
                <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
            </div>
            <div class="form-group">
                <a href="{{ url_for('user.register') }}" class="signup-link">没有账号？立即注册</a>
                <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/front/post_detail.html
{% extends 'front/base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/post_detail.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间：{{ post.create_time }}</span>
                <span>作者：<a href="{{ url_for('user.profile',user_id=post.author.id) }}">{{ post.author.username }}</a></span>
                <span>所属板块：{{ post.board.name }}</span>
                <span>阅读数：{{ post.read_count }}</span>
                <span>评论数：{{ post.comments.count() }}</span>
            </p>
            <article class="post-content" id="post-content">
                {{ post.content|safe }}
            </article>
{#            |safe 是一个过滤器，用于告诉模板引擎不要对内容进行转义，直接输出原始内容。#}
        </div>
        <div class="comment-group">
            <h3>评论列表</h3>
            <ul class="comment-list-group">
                {% for comment in post.comments.filter_by(is_active=True) %}
                    <li>
                        <div class="comment-content">
                            <p class="author-info">
                                <span>{{ comment.author.username }}</span>
                                <span>{{ comment.create_time }}</span>
                            </p>
                            <p class="comment-txt">
                                {{ comment.content }}
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="add-comment-group">
            <h3>发表评论</h3>
            <form action="{{ url_for('front.public_comment',post_id=post.id) }}" method="post">
                <textarea class="form-control" name="content" id="editor" cols="30" rows="5"></textarea>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="text-danger mt-2">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="comment-btn-group">
                    <button class="btn btn-primary" id="comment-btn">发表评论</button>
                </div>
            </form>
        </div>
    </div>
    <div class="sm-container"></div>
{% endblock %}

templates/front/profile.html
{% extends 'front/base.html' %}

{% block title %}
        {{ user.username }}个人中心
{% endblock %}

{% block head %}
    <style>
        .profile-box {
            width: 400px;
            margin: 0 auto;
        }

        .avatar {
            width: 100px;
        }
    </style>
    <script src="{{ url_for('static',filename='front/js/profile.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="profile-box">
        <h1 style="text-align: center;">{{ user.username }}个人中心</h1>

        <table class="table table-bordered mt-5">
            <tbody>
            <tr>
                <th style="color: #FFAE42">发帖数量：</th>
                <td>
                    <div class="comment-btn-group">
                        <button class="btn btn-primary" id="comment-state-btn">查询评论情况</button>
                        {#                            <button class="btn btn-primary" id="comment-state-btn" formaction="../../view/user_comments_view">查询评论情况</button>#}
                    </div>

                </td>
            </tr>
            </tbody>
        </table>

        <form action="{{ url_for('user.edit_profile') }}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <table class="table table-bordered mt-5">
                <tbody>
                <tr>
                    <th width="100px" style="color: #FFAE42">用户名：</th>
                    <td>
                        {% if is_mine %}
                            <input type="text" name="username" value="{{ user.username }}">
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th style="color: #FFAE42">头像：</th>
                    <td>
                        {% if user.avatar %}
                            <img src="{{ user.avatar }}" alt="">
                        {% else %}
                            <img class="avatar"
                                 src="{{ avatars.gravatar(user.email|email_hash)|replace('https://gravatar.com/avatar/','https://cdn.v2ex.com/gravatar/') }}"
                                 alt="">
                        {% endif %}
                        {% if is_mine %}
                            <input type="file" name="avatar_root" accept="image/jpeg, image/png" value="上传头像"><br>
                            <input type="text" name="avatar" value="上传头像链接">
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th style="color: #FFAE42">签名：</th>
                    <td>
                        {% if is_mine %}
                            <input type="text" name="signature" value="{{ user.signature or '' }}">
                        {% else %}
                            {{ user.signature or "" }}
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
            {% if is_mine %}
                <div style="text-align: center;">
                    <button class="btn btn-primary">保存</button>
                </div>
            {% endif %}
        </form>

    </div>
{% endblock %}