models/post.py
from exts import db
from datetime import datetime
from sqlalchemy import text


# 板块模型
class BoardModel(db.Model):
    def __init__(self, *args, **kwargs):
        self.id = kwargs.get('id')
        self.name = kwargs.get('name')
        self.create_time = kwargs.get('create_time')
        self.is_active = kwargs.get('is_active')

    __tablename__ = 'board'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(20), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    is_active = db.Column(db.Boolean, default=True)


# 帖子模型
class PostModel(db.Model):
    def __init__(self, *args, **kwargs):
        self.id = kwargs.get('id')
        self.title = kwargs.get('title')
        self.content = kwargs.get('content')
        self.create_time = kwargs.get('create_time')
        self.read_count = kwargs.get('read_count')
        self.is_active = kwargs.get('is_active')
        self.board_id = kwargs.get('board_id')
        self.author_id = kwargs.get('author_id')

    __tablename__ = 'post'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    read_count = db.Column(db.Integer, default=0)
    is_active = db.Column(db.Boolean, default=True)
    board_id = db.Column(db.Integer, db.ForeignKey("board.id"))
    author_id = db.Column(db.String(100), db.ForeignKey("user.id"), nullable=False)

    board = db.relationship("BoardModel", backref="posts")
    author = db.relationship("UserModel", backref='posts')



# 评论模型
class CommentModel(db.Model):
    def __init__(self, *args, **kwargs):
        self.id = kwargs.get('id')
        self.content = kwargs.get('content')
        self.create_time = kwargs.get('create_time')
        self.post_id = kwargs.get('post_id')
        self.author_id = kwargs.get('author_id')
        self.is_active = kwargs.get('is_active')

    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    post_id = db.Column(db.Integer, db.ForeignKey("post.id"))
    author_id = db.Column(db.String(100), db.ForeignKey("user.id"), nullable=False)
    is_active = db.Column(db.Boolean, default=True)

    post = db.relationship("PostModel", backref=db.backref('comments', order_by=create_time.desc(), lazy="dynamic"))
    author = db.relationship("UserModel", backref='comments')

forms/baseform.py
from wtforms import Form


class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors)
        return message_list

    # 这段代码定义了一个表单基类BaseForm，
    # 它添加了一个messages属性，该属性收集表单中所有字段的错误消息，并以列表的形式返回它们。这可以用于在用户界面上显示错误消息。

forms/cms.py
from .baseform import BaseForm
from wtforms import StringField, IntegerField, BooleanField
from wtforms.validators import Email, InputRequired, Length


class AddStaffForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确格式的邮箱！")])
    role = IntegerField(validators=[InputRequired(message="请选择角色！")])


class EditStaffForm(BaseForm):
    is_staff = BooleanField(validators=[InputRequired(message="请选择是否为员工！")])
    role = IntegerField(validators=[InputRequired(message="请选择分组！")])


class EditBoardForm(BaseForm):
    board_id = IntegerField(validators=[InputRequired(message="请输入板块ID！")])
    name = StringField(validators=[Length(min=1, max=20, message="请输入1-20位长度！")])


class PublicBoardNameForm(BaseForm):
    BoardName = StringField(validators=[Length(min=1, max=200, message="请输入板块的名称！")])

forms/post.py
from .baseform import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import InputRequired, Length


class PublicPostForm(BaseForm):
    title = StringField(validators=[Length(min=2, max=100, message='请输入正确长度的标题！')])
    content = StringField(validators=[Length(min=2, message="请输入正确长度的内容！")])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])


class PublicCommentForm(BaseForm):
    content = StringField(validators=[Length(min=2, max=200, message="请输入正确长度的评论！")])

forms/user.py
import wtforms  # 导入 wtforms 库
from wtforms import StringField, ValidationError, BooleanField, FileField
from wtforms.validators import Email, EqualTo, Length, InputRequired
from flask_wtf.file import FileAllowed
from exts import cache
from models.user import UserModel
from models.email import EmailCaptchaModel
from .baseform import BaseForm
from exts import db  # 导入数据库扩展对象


class RegisterForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确格式的邮箱！")])
    captcha = StringField(validators=[Length(min=6, max=6, message="请输入正确格式的验证码！")])
    username = StringField(validators=[Length(min=2, max=20, message="请输入正确长度的用户名！")])
    password = StringField(validators=[Length(min=6, max=20, message="请输入正确长度的密码！")])
    confirm_password = StringField(validators=[EqualTo("password", message="两次密码不一致！")])

    # def validate_email(self, field):
    #     email = field.data
    #     user = UserModel.query.filter_by(email=email).first()
    #     if user:
    #         raise ValidationError(message="邮箱已经存在")

    # 自定义验证方法：检查邮箱是否已经被注册
    def validate_email(self, field):
        """检查邮箱是否已经被注册"""
        email = field.data
        # field.data可以获取用户输入的值
        user = UserModel.query.filter_by(email=email).first()  # 在数据库中查询是否已存在该邮箱
        # filter_by(email=email): 这是一个过滤器，它告诉数据库只选择那些邮箱与指定邮箱相匹配的用户。email是传入的参数，用于与数据库中的邮箱进行比较。
        # first(): 这是查询的一个方法，它告诉数据库只返回满足条件的第一个结果。如果没有符合条件的结果，它会返回 None。
        if user:
            raise wtforms.ValidationError(message="该邮箱已经被注册!")  # 若存在，抛出验证错误

    # def validate_captcha(self, field):
    #     captcha = field.data
    #     email = self.email.data
    #     cache_captcha = cache.get(email)
    #     if not cache_captcha or captcha != cache_captcha:
    #         raise ValidationError(message="验证码错误！")

    # 自定义验证方法：检查验证码是否正确
    def validate_captcha(self, field):
        """检查验证码是否正确"""
        captcha = field.data
        email = self.email.data
        captcha_model = EmailCaptchaModel.query.filter_by(email=email, captcha=captcha).first()  # 在数据库中查询验证码是否正确
        if not captcha_model:
            raise wtforms.ValidationError(message="邮箱或验证码错误!")  # 若验证码不正确，抛出验证错误
        else:
            # TODO: 可以删除 captcha_model，占用时间，可以写一个脚本定期删除
            db.session.delete(captcha_model)
            db.session.commit()


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确格式的邮箱！")])
    password = StringField(validators=[Length(min=6, max=20, message="请输入正确长度的密码！")])
    remember = BooleanField()


class EditProfileForm(BaseForm):
    username = StringField(validators=[Length(min=2, max=20, message="请输入正确格式的用户名！")])
    avatar_root = FileField(validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'], message="文件类型错误！")])
    avatar = StringField(validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'], message="文件类型错误！")])
    signature = StringField()

    def validate_signature(self, field):
        signature = field.data
        if signature and len(signature) > 100:
            raise ValidationError(message="签名不能超过100个字符")

blueprints/cms.py
from MySQLdb import IntegrityError
from flask import Blueprint, g, redirect, render_template, request, flash, url_for
from flask_wtf import csrf

from models.user import PermissionEnum
from models.user import UserModel, RoleModel
from models.post import PostModel, CommentModel, BoardModel
from forms.cms import AddStaffForm, EditStaffForm, EditBoardForm, PublicBoardNameForm
from exts import db
from decorators import permission_required
from utils import restful

bp = Blueprint("cms", __name__, url_prefix="/cms")


@bp.before_request
def cms_before_request():
    if not hasattr(g, "user") or g.user.is_staff == False:
        return redirect("/")


@bp.context_processor
def cms_context_processor():
    return {"PermissionEnum": PermissionEnum}


@bp.get("")
def index():
    return render_template("cms/index.html")


@bp.get("/staff/list")
@permission_required(PermissionEnum.CMS_USER)
def staff_list():
    users = UserModel.query.filter_by(is_staff=True).all()
    return render_template("cms/staff_list.html", users=users)


@bp.route("/staff/add", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def add_staff():
    if request.method == "GET":
        roles = RoleModel.query.all()
        return render_template("cms/add_staff.html", roles=roles)
    else:
        form = AddStaffForm(request.form)
        if form.validate():
            email = form.email.data
            role_id = form.role.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                flash("没有此用户！")
                return redirect(url_for("cms.add_staff"))
            user.is_staff = True
            user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.add_staff"))
            # """跳转没实现"""
            # return redirect(url_for("cms.staff_list"))


@bp.route("/board/add_board", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def add_board():
    #  TODO:要新建板块
    if request.method == "GET":
        # roles = RoleModel.query.all()
        return render_template("cms/edit_board.html")
    else:
        # 处理表单提交的数据
        # category_name = request.form['category_name']
        # 这里可以根据表单提交的数据执行相应的操作，比如保存到数据库中
        form = PublicBoardNameForm(request.form)
        if form.validate():
            BoardName = form.BoardName.data
            curr_board = BoardModel.query.filter_by(name=BoardName).first()
            if curr_board:
                flash('不能输入同一个板块名', 'error')
                print("不能输入同一个板块名")
                return redirect(url_for('cms.add_board'))
            board = BoardModel(name=BoardName)
            db.session.add(board)
            db.session.commit()
            boards = BoardModel.query.all()
            return redirect(url_for('cms.add_board'))
            # return render_template("cms/boards.html", boards=boards)
            # return redirect(url_for("cms.board_list"))  # 假设 '/board_list' 是 'cms.board_list' 的 URL
        # return redirect(url_for('cms.board_list'))
        # return redirect(url_for('cms.board_list'))
        """跳转没实现"""
        # return redirect(url_for("cms.board_list"))  # 假设 '/board_list' 是 'cms.board_list' 的 URL


@bp.get("/boards")
@permission_required(PermissionEnum.BOARD)
def board_list():
    boards = BoardModel.query.all()
    return render_template("cms/boards.html", boards=boards)


@bp.route("/staff/update", methods=['POST'])
@permission_required(PermissionEnum.CMS_USER)
def update_staff():
    pass


@bp.route("/staff/edit/<string:user_id>", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def edit_staff(user_id):
    user = UserModel.query.get(user_id)
    if request.method == 'GET':
        roles = RoleModel.query.all()
        return render_template("cms/edit_staff.html", this_user_id=user_id, user=user, roles=roles)
    else:
        form = EditStaffForm(request.form)
        if form.validate():
            is_staff = form.is_staff.data
            role_id = form.role.data

            user.is_staff = is_staff
            if user.role.id != role_id:
                user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.edit_staff", user_id=user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("cms.edit_staff", user_id=user_id))


@bp.route("/staff/edit1/<string:user_id>", methods=['POST'])
@permission_required(PermissionEnum.CMS_USER)
def edit_staff1(user_id):
    # user = UserModel.query.get(user_id)
    # form = EditStaffForm(request.form)
    # if form.validate():
    #     is_staff = form.is_staff.data
    #     role_id = form.role.data
    #
    #     user.is_staff = is_staff
    #     if user.role.id != role_id:
    #         user.role = RoleModel.query.get(role_id)
    #     db.session.commit()
    #     return redirect(url_for("cms.edit_staff", user_id=user_id))
    # else:
    #     for message in form.messages:
    #         flash(message)
    #     return redirect(url_for("cms.edit_staff", user_id=user_id))

    role_id = request.form.get("role_id", type=int)
    my_user = request.form.get("user_id", type=int)
    if role_id == None:
        return restful.params_error(message="请传入role_id参数！")
    user = UserModel.query.filter_by(id=user_id).first()

    if user is None:
        return restful.params_error(message="未找到对应的用户！")

    user.role_id = role_id
    db.session.commit()
    return restful.ok()


@bp.route("/staff/edit2/<string:user_id>", methods=['POST'])
@permission_required(PermissionEnum.CMS_USER)
def edit_staff2(user_id):
    is_staff = request.form.get("isstaff", type=int)
    my_user = request.form.get("user_id", type=int)
    if is_staff == None:
        return restful.params_error(message="请传入role_id参数！")
    user = UserModel.query.filter_by(id=user_id).first()

    if user is None:
        return restful.params_error(message="未找到对应的用户！")

    user.is_staff = is_staff
    user.role_id = None
    db.session.commit()
    return restful.ok()


@bp.route("/staff/add_role", methods=['POST'])
@permission_required(PermissionEnum.CMS_USER)
def add_role():
    inputEmail = request.form.get("inputEmail")
    role_id = request.form.get("role_id", type=int)
    if inputEmail == None:
        return restful.params_error(message="请传入inputEmail参数！")
    user = UserModel.query.filter_by(email=inputEmail).first()

    if user is None:
        return restful.params_error(message="未找到对应的用户！")

    user.role_id = role_id
    user.is_staff = 1
    db.session.commit()
    return restful.ok()


@bp.route("/users")
@permission_required(PermissionEnum.FRONT_USER)
def user_list():
    users = UserModel.query.filter_by(is_staff=False).all()  # 不显示员工
    return render_template("cms/users.html", users=users)


@bp.post("/users/active/<string:user_id>")
@permission_required(PermissionEnum.FRONT_USER)
def active_user(user_id):
    is_active = request.form.get("is_active", type=int)
    if is_active == None:
        return restful.params_error(message="请传入is_active参数！")
    user = UserModel.query.get(user_id)
    user.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()


@bp.get('/posts')
@permission_required(PermissionEnum.POST)
def post_list():
    posts = PostModel.query.all()
    return render_template("cms/posts.html", posts=posts)


@bp.post('/posts/active/<int:post_id>')
@permission_required(PermissionEnum.POST)
def active_post(post_id):
    is_active = request.form.get("is_active", type=int)
    if is_active == None:
        return restful.params_error(message="请传入is_active参数！")
    post = PostModel.query.get(post_id)
    post.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()


@bp.get('/comments')
@permission_required(PermissionEnum.COMMENT)
def comment_list():
    comments = CommentModel.query.all()
    return render_template("cms/comments.html", comments=comments)


@bp.post('/comments/active/<int:comment_id>')
@permission_required(PermissionEnum.COMMENT)
def active_comment(comment_id):
    is_active = request.form.get("is_active", type=int)
    if is_active == None:
        return restful.params_error(message="请传入is_active参数！")
    comment = CommentModel.query.get(comment_id)
    comment.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()


# 这个实现的是删除板块
@bp.post('/board/delete/<int:board_id>')
@permission_required(PermissionEnum.CMS_USER)
def withdraw_board(board_id):
    try:
        # 查询模块
        board = BoardModel.query.filter_by(id=board_id).first()  # post返回值为course_id主键查询的帖子
        if board is None:
            raise Exception('Course not found.')
        # 删除关联的帖子记录
        enrollments = PostModel.query.filter_by(board_id=board_id).all()

        for enrollment in enrollments:
            # 删除相关的评论
            comments = CommentModel.query.filter_by(post_id=enrollment.id).all()
            for comment in comments:
                db.session.delete(comment)
            db.session.delete(enrollment)

        # 删除模块
        db.session.delete(board)
        # 提交事务
        db.session.commit()
        return restful.ok()
    except Exception as e:
        # 出现异常时回滚事务
        db.session.rollback()
        return 'Course withdrawal failed: ' + str(e)


# @bp.post('/board/delete/<int:board_id>')
# @permission_required(PermissionEnum.CMS_USER)
# def withdraw_board(board_id):
#     try:
#         with db.session.begin():
#             # 查询模块
#             board = BoardModel.query.filter_by(id=board_id).first()
#             if board is None:
#                 raise Exception('Board not found.')
#
#             # 删除关联的帖子记录
#             PostModel.query.filter_by(board_id=board_id).delete()
#
#             # 删除模块
#             db.session.delete(board)
#
#             return restful.ok()
#
#     except IntegrityError as e:
#         db.session.rollback()

templates/cms/add_staff.html
{% extends "cms/base.html" %}

{% block title -%}
    添加员工
{%- endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='cms/js/add_staff.js') }}"></script>
{% endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}

{% block main_content %}
    {#    <form action="" method="post">#}
    <form style="color: #FFAE42">
        <div class="form-container">
            <div class="form-group form-inline">
                <label for="email">邮箱：</label>
                <input id="email" type="email" class="form-control" name="email" placeholder="邮箱">
            </div>
            <div class="form-group">
                <label>角色：</label>
                {% for role in roles %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="role" id="inlineRadio{{ loop.index }}"
                               value="{{ role.id }}">
                        <label class="form-check-label" for="inlineRadio{{ loop.index }}">{{ role.name }}</label>
                    </div>
                {% endfor %}
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="submit">立即添加</button>
            </div>
        </div>
    </form>
    <div id="staff_list_link" data-url="{{ url_for('cms.staff_list') }}"></div>
{% endblock %}

templates/cms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static',filename='common/zlajax.js') }}"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='cms/css/base.css') }}">
    <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='front/css/custom.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">南开大学校园集市CMS管理系统</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a href="{{ url_for('user.profile',user_id=g.user.id) }}" class="nav-link">{{ g.user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">前台首页</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
            </li>
        </ul>
    </div>
</nav>
{#<div class="mouse"></div> <!-- 使用一个 div 元素作为鼠标指针 -->#}
<div class="main-body">
    <div class="left-body">
        <div class="sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                {% set user = g.user %}
                {% if user.has_permission(PermissionEnum.POST) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.post_list') }}">帖子管理</a></li>
                {% endif %}
                {% if user.has_permission(PermissionEnum.COMMENT) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comment_list') }}">评论管理</a></li>
                {% endif %}
                {% if user.has_permission(PermissionEnum.BOARD) %}
                    <li class="board-manage"><a href="{{ url_for('cms.board_list') }}">板块管理</a></li>
                {% endif %}
                {% if user.has_permission(PermissionEnum.FRONT_USER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.user_list') }}">用户管理</a></li>
                {% endif %}
                {% if user.has_permission(PermissionEnum.CMS_USER) %}
                    <li class="nav-group UserModel-manage"><a href="{{ url_for('cms.staff_list') }}">员工管理</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="right-body">
        <div class="main">
            <h1 style="color: white">{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/boards.html
{% extends 'cms/base.html' %}

{% block title %}板块管理{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='cms/js/boards.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='cms/css/boards.css') }}">
    <style>
        .modal-content {
            border-radius: 10px; /* 圆角边框 */
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3); /* 添加阴影效果 */
        }

        .modal-header {
            background-color: #f8d7da; /* 头部背景色 */
            color: #721c24; /* 文字颜色 */
            border-color: #f5c6cb; /* 边框颜色 */
        }

        .modal-title {
            font-size: 1.25rem; /* 标题字体大小 */
        }

        .modal-body p {
            color: #495057; /* 文字颜色 */
        }

        .modal-footer {
            background-color: #fff; /* 底部背景色 */
            border-top: 1px solid #e9ecef; /* 上边框 */
        }

        /* 确保模态框内的按钮有统一的样式 */
        .btn-secondary {
            background-color: #6c757d;
            border-color: #6c757d;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
            border-color: #545b62;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}

    <script>
        // 检查是否有闪现消息
        $(document).ready(function () {
            // 假设你已经有一种方法来获取闪现消息
            var errorMessage = '{{ get_flashed_messages(category_filter=["error"]) | join(" ") }}';
            if (errorMessage) {
                // 使用 Bootstrap 的模态框显示错误消息
                $('#errorModal').modal('show');
                // 或者使用 jQuery UI 的对话框
                // $('#errorDialog').dialog('open');
            }
        });
    </script>

    <!-- Bootstrap 模态框 -->
    <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">输入错误</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="error-message">{{ get_flashed_messages(category_filter=["error"]) | join(" ") }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">确定</button>
                </div>
            </div>
        </div>
    </div>


    <form action="{{ url_for('cms.add_board') }}" method="post">
        <div class="top-box">
            {#            <button class="btn btn-primary" id="add-board-btn">添加新板块</button>#}
            <a href="{{ url_for('cms.add_board') }}" class="btn btn-primary mb-3">添加新板块</a>
        </div>
    </form>
    <table class="table table-bordered" style="color: #FFAE42">
        <thead>
        <tr>
            <th style="color: #FFAE42">板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>{{ board.posts|length }}</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-sm edit-board-btn" data-board-id="{{ board.id }} "
                            data-board-name="{{ board.name }}">编辑
                    </button>
                    <button class="btn btn-danger btn-sm delete-board-btn" data-board-id="{{ board.id }}">删除
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/change_post.html
{% extends "cms/base.html" %}

{% block title -%}
    修改帖子
{%- endblock %}

{% block head %}
    {#    <script src="{{ url_for('static',filename='cms/js/edit_staff.js') }}"></script>#}
{% endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}

{% block main_content %}
    <h2 style="color: #db4055">修改帖子所属板块</h2>
    {#    <form action="{{ url_for('cms.edit_staff',user_id=user.id) }}" method="post">#}
    <form action="{{ url_for('cms.change_post_belong') }}" method="POST" style="color: #FFAE42">
{#        {{ form.csrf_token }}#}
        <div>
            <label for="original_name">原帖子所属板块类型名称：</label><br>
            <p>{{ board_name }}</p>
            <input type="text" id="original_board_name" name="original_board_name" required><br>

            {#            <input type="text" id="original_name" name="original_name" required><br>#}
        </div>
        <div>
            <label for="new_name">新所属板块类型名称：：</label><br>
            <input type="text" id="new_name" name="new_name" required><br>
        </div>
        <div>
            <label for="reason">理由：</label><br>
            <textarea id="reason" name="reason" rows="4" cols="50"></textarea><br>
        </div>
        <div>
            <label for="contact">联系方式：</label><br>
            <input type="text" id="contact" name="contact"><br>
        </div>
        <br>
        <input type="submit" value="提交">
    </form>
{% endblock %}

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    南开大学校园集市CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到南开大学校园集市CMS管理系统
{% endblock %}